"vim-plug
call plug#begin(has('win32') ? '~/vimfiles/plugged' : '~/.vim/plugged')
Plug 'dense-analysis/ale'
Plug 'fatih/vim-go'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
call plug#end()

"preload
if has('win32') | set enc=utf-8 | endif

"options
set backspace=indent,start
set backupcopy=yes nobackup noundofile
set expandtab shiftwidth=2 softtabstop=2 tabstop=8
set cursorline cursorlineopt=number
set fillchars=stl:=,stlnc:-,vert:\|,fold:-
set hlsearch
set laststatus=2
set list listchars=tab:·\ ,trail:~
set noincsearch
set numberwidth=2
set showcmd
set splitbelow splitright
set statusline=[%<%f:%l:%c]%m%r%q%w%=%a%y[%n]
set textwidth=80 colorcolumn=+1
set wildmenu wildignorecase wildignore=.git/,.*.sw[a-p],.keep

let c_syntax_for_h = 1

nnoremap Q <nop>
nnoremap Ñ :
nnoremap <Leader>q :let @/=''<CR>

let g:copyprg = 'xclip -i -sel c'
let g:pasteprg = 'xclip -o -sel c'
nnoremap <Leader>xc :call system(g:copyprg, @")<CR>
nnoremap <Leader>xv :exec 'normal i'.substitute(system(g:pasteprg), '[\r\n]*$', '', '')<CR>

augroup vimrc_reload
  au!
  au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC
    \ | if has('gui_running') && !empty($MYGVIMRC) | so $MYGVIMRC | endif
augroup END

augroup fo_clean
  au!
  au FileType * set fo-=o
augroup END

"terminal
nnoremap <Leader>tj :terminal<CR>
nnoremap <Leader>tl :vertical terminal<CR>
nnoremap <Leader>th :vertical terminal<CR><C-w>H

"netrw
let g:netrw_list_hide = '^\.\.\?[\/]$,'.netrw_gitignore#Hide()
let g:netrw_hide = 1
"let g:netrw_sort_sequence = '[\/]$,\.\(h\|c\)$,*'
let g:netrw_sort_sequence = '[\/]$,*'
nnoremap <Leader>ee :Explore .<CR>
nnoremap <Leader>er :Rexplore<CR>
nnoremap <Leader>ev :Vexplore .<CR>

"dense-analysis/ale
let g:ale_echo_msg_format = '(%linter%/%code%) %s'
let g:ale_set_ballons = 0
"let g:ale_hover_to_preview = 1
let g:ale_lint_on_enter = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_text_changed = 'never'
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
nmap <Leader>ad <Plug>(ale_detail)
nmap <Leader>af <Plug>(ale_fix)
nmap <Leader>aj <Plug>(ale_next)
nmap <Leader>ak <Plug>(ale_previous)
nmap <Leader>al <Plug>(ale_lint)
nmap <Leader>an <Plug>(ale_next_wrap)
nmap <Leader>ap <Plug>(ale_previous_wrap)
nmap <Leader>ag <Plug>(ale_go_to_definition)
nmap <Leader>aG <Plug>(ale_go_to_type_definition)
nmap <Leader>aG <Plug>(ale_lint_on_insert_leave)
nnoremap <Leader>ai :ALEInfo<CR>

"fatih/vim-go
let g:go_addtags_transform = 'camelcase'
let g:go_imports_autosave = 0
let g:go_template_autocreate = 0
nnoremap <Leader>gi :GoImports<CR>
nnoremap <Leader>gt :GoAddTags<CR>

"environment
set background=dark
colorscheme default
