#!/usr/bin/env bash

_me_load() {
  local type="${1#me_}"
  COMPREPLY+=($(cd $ME_DIR/bash/$type &>/dev/null;
    compgen -G "$2*.sh" | xargs -r basename -s .sh))
}

complete -F _me_load me_plugin
complete -F _me_load me_lib
