#!/usr/bin/env bash

DIR=$(cd `dirname $BASH_SOURCE`; pwd -P)

if [[ $# -lt 1 ]]; then
  echo "Usage: `basename $BASH_SOURCE` KEY" >&2
  exit 1
fi

if [[ `uname -s` == Darwin ]]; then
  sed -i '' "/\[$1\]/d" "$DIR/me.var"
else
  sed -i    "/\[$1\]/d" "$DIR/me.var"
fi
