alias r="rails"
alias rk="rake"
alias rkrr="rake db:drop db:create db:migrate db:seed"
alias rkin="rake db:create db:migrate db:seed"
alias rs0="rails server -b 0.0.0.0"
alias rps="ps -aux | grep rails"
alias rkrg="rake routes | grep "
alias rgrep="rgrep --color=auto --exclude-dir=log --exclude-dir=.git --exclude-dir=tmp -In"
