case $- in
  *i*) ;;
  *) return;;
esac

# BASH
# ----
HISTFILE=
HISTCONTROL=ignoreboth:erasedups
shopt -s checkwinsize
shopt -s histappend
shopt -s histverify

# SETUP
# -----
lib=(user git)
plugin=(user kak smart ls mancolor)
theme="monal"
. $(dirname `readlink -f ${BASH_SOURCE}`)/loader.sh
