# SETUP
# ------
export CARLSH="$HOME/gitlab.com/cjgajard/configfiles"

library=(mfind python)
plugin=(autojump colorauto ls nvm django rbenv rails)

PS1='\[\e[01;34m\]\W\[\e[00m\]\$ '
source $CARLSH/bash/loader.sh

# BASH SETTING
# ------------
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000

# USER
# ----
export PATH="$PATH:$HOME/.local/bin"
