case $- in
  *i*) ;;
  *) return;;
esac

# SETUP
# -----
export REPO="$HOME/Documents"

library=(git mfind)
plugin=(autojump colorauto ls)
smart_plugin=true
theme="dual"
source $REPO/cjgajard/configfiles/bash/loader.sh

# BASH
# ----
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000
